import { Project } from '@/interfaces/Project'

export const Projects: Project[] = [
  {
    title: 'Bookmarks RESTful API',
    description: 'A RESTful API for managing bookmarks, built with NestJS.',
    tech: ['NestJs', 'TypeScript', 'Prisma', 'PostgreSQL', 'JWT', 'Pactum', 'Jest'],
    githubUrl: 'https://github.com/AQA20/bookmarks-api',
    image: '/bookmarks.png',
    type: 'image',
  },
  {
    title: 'Select Skips Page Stepper',
    description: 'A stepper page to select a skip',
    tech: ['React', 'Vite', 'Vercel',],
    liveUrl: 'https://rem-waste-skips.vercel.app/',
    githubUrl: 'https://github.com/AQA20/rem-waste-skips',
    image: '/RemWaste/selectSkipsStepper.png',
    type: 'image',
  },
  {
    title: 'Select Skips Page',
    description: 'A page to select a skip',
    tech: ['React', 'Vite', 'Vercel',],
    liveUrl: 'https://rem-waste-inky.vercel.app/',
    githubUrl: 'https://github.com/AQA20/rem-waste',
    image: '/RemWaste/selectSkips.png',
    type: 'image',
  },
  {
    title: 'User Booking Page',
    description: 'A new booking use page',
    tech: ['PHP', 'MySQL', 'Laravel', 'Vue', 'Tailwind', 'Vuetify'],
    video: '/filtered&paginated-tickets.webm',
    liveUrl: '#',
    images: [
      '/tripsome/userBookingPage0.png',
      '/tripsome/userBookingPage1.png',
      '/tripsome/userBookingPage2.png',
      '/tripsome/userBookingPage3.png',
    ],
    type: 'images',
  },
  {
    title: 'Paginated & Filterable Booking Tickets',
    description: 'A new booking flow for a travel booking platform',
    tech: ['PHP', 'MySQL', 'Laravel', 'Vue', 'Tailwind', 'Vuetify'],
    video: '/filtered&paginated-tickets.webm',
    liveUrl: 'https://tripsome.az/en/activities',
    type: 'video',
  },
  {
    title: 'Booking flow',
    description: 'A new booking flow for a travel booking platform',
    tech: ['PHP', 'MySQL', 'Laravel', 'Vue', 'Tailwind', 'Vuetify'],
    image: '/500kalima.png',
    liveUrl: 'https://tripsome.az/en/activities',
    images: [
      '/tripsome/0.png',
      '/tripsome/1.png',
      '/tripsome/2.png',
      '/tripsome/3.png',
    ],
    type: 'images',
  },
  {
    title: 'Blog',
    description: 'A blog website',
    tech: ['Next.js', 'React', 'JavaScript', 'Tailwind'],
    image: '/500kalima.png',
    githubUrl: 'https://github.com/AQA20/500kalima',
    liveUrl: 'https://500kalima.com',
    type: 'image',
  },
  {
    title: 'Blog CMS',
    description: 'A blog content management system',
    tech: ['Next.js', 'React', 'TypeScript', 'Tailwind', 'Shadcn'],
    image: '/500kalima-cms.png',
    githubUrl: 'https://github.com/AQA20/blog-cms',
    liveUrl: 'https://manage.500kalima.com',
    type: 'image',
  },
  {
    title: 'Blog API',
    description: 'Node.js and Express.js RESTful API for a blog',
    tech: ['Node.js', 'Express.js', 'AWS', 'MySql', 'Sequelize'],
    image: '/node-api.png',
    githubUrl: 'https://github.com/AQA20/blog-api',
    liveUrl: '#',
    type: 'image',
  },
]
